module(
    name = "extensions_sdk",
    version = "1.0.0",
)

bazel_dep(name = "rules_go", version = "0.59.0")
bazel_dep(name = "gazelle", version = "0.40.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.25.0")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.module(
    path = "github.com/extism/go-pdk",
    sum = "h1:DNP/9ugbNiXyBiMrNdMl/TF9J85uh0DC7sFnMuNZ/Ls=",
    version = "v1.1.2",
)
go_deps.module(
    path = "google.golang.org/protobuf",
    sum = "h1:yBPeRvTftaleIgM3PZ/WBIZ7XM/eEYAaEyCwvyjq/gk=",
    version = "v1.36.1",
)
use_repo(
    go_deps,
    "com_github_extism_go_pdk",
    "org_golang_google_protobuf",
)

bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "aspect_rules_js", version = "3.1.2")
bazel_dep(name = "aspect_rules_ts", version = "3.8.10")
bazel_dep(name = "rules_nodejs", version = "6.2.0")
bazel_dep(name = "aspect_rules_rollup", version = "2.0.1")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "sdk_npm",
    pnpm_lock = "//wasm-extension-js:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
npm.npm_translate_lock(
    name = "proto_npm",
    pnpm_lock = "//protos:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "sdk_npm", "proto_npm")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
use_repo(node, "nodejs_toolchains")

register_toolchains("@nodejs_toolchains//:all")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    name = "sdk_npm_typescript",
    ts_version_from = "//wasm-extension-js:package.json",
)
use_repo(rules_ts_ext, npm_typescript = "sdk_npm_typescript")

register_toolchains("@npm_typescript//:all")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
)
use_repo(python, "python_3_11")

bazel_dep(name = "aspect_rules_py", version = "1.11.5")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "extism_js_binary_download",
    downloaded_file_path = "extism-js.gz",
    urls = ["https://github.com/extism/js-pdk/releases/download/v1.2.0/extism-js-x86_64-linux-v1.2.0.gz"],
)

http_archive(
    name = "extism_py_tool",
    build_file_content = """
exports_files(["bin/extism-py"])
filegroup(
    name = "share_files",
    srcs = glob(["share/extism-py/**"]),
    visibility = ["//visibility:public"],
)
""",
    sha256 = "24fa8a4a2f2fe25e3a95a4dc1dbd10a4c30e97697102fec45c59bfc743b2d9d4",
    strip_prefix = "extism-py",
    urls = ["https://github.com/extism/python-pdk/releases/download/v0.1.5/extism-py-x86_64-linux-v0.1.5.tar.gz"],
)

http_archive(
    name = "binaryen_tool",
    build_file_content = """
filegroup(
    name = "bin_files",
    srcs = glob(["bin/**"]),
    visibility = ["//visibility:public"],
)
""",
    sha256 = "c55b74f3109cdae97490faf089b0286d3bba926bb6ea5ed00c8c784fc53718fd",
    strip_prefix = "binaryen-version_116",
    urls = ["https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz"],
)

http_archive(
    name = "mdbook_tool",
    build_file_content = """
exports_files(["mdbook"])
""",
    sha256 = "9ef07fd288ba58ff3b99d1c94e6d414d431c9a61fdb20348e5beb74b823d546b",
    urls = ["https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz"],
)

http_archive(
    name = "mdbook_admonish_tool",
    build_file_content = """
exports_files(["mdbook-admonish"])
""",
    integrity = "sha256-XRnsY3bGRiBCNfGXyROYz5WHPpbmEAmCE3ESBW2pb+Q=",
    urls = ["https://github.com/tommilligan/mdbook-admonish/releases/download/v1.18.0/mdbook-admonish-v1.18.0-x86_64-unknown-linux-gnu.tar.gz"],
)

bazel_dep(name = "rules_rust", version = "0.68.1")
single_version_override(
    module_name = "rules_rust",
    patch_strip = 1,
    patches = ["//patches:rules_rust_gnu_windows.patch"],
    version = "0.68.1",
)
bazel_dep(name = "moosync")
git_override(
    module_name = "moosync",
    remote = "https://github.com/Moosync/Moosync",
    branch = "main",
)

bazel_dep(name = "moosync_ext", version = "0.0.1")
git_override(
    module_name = "moosync_ext",
    remote = "https://github.com/Moosync/moosync-exts",
    branch = "bazel",
)

bazel_dep(name = "rules_rust_prost", version = "0.68.1")
bazel_dep(name = "protobuf", version = "33.2", repo_name = "com_google_protobuf")
single_version_override(
    module_name = "protobuf",
    version = "33.2",
)
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "bazel_env.bzl", version = "0.1.1")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    extra_target_triples = [
        "wasm32-wasip1",
        "x86_64-linux-android",
        "aarch64-linux-android",
        "x86_64-pc-windows-gnu",
    ],
    versions = [
        "1.95.0",
        "nightly/2025-12-16",
    ],
)
use_repo(
    rust,
    "rust_toolchains",
)

rust_host_tools = use_extension("@rules_rust//rust:extensions.bzl", "rust_host_tools")
rust_host_tools.host_tools(
    name = "mooync_edk_host_tools",
    version = "nightly",
)
use_repo(
    rust_host_tools,
    "mooync_edk_host_tools",
)

register_toolchains("@rust_toolchains//:all")

sdk_wasm_crates = use_extension("@rules_rust//crate_universe:extension.bzl", "crate", isolate = True)
sdk_wasm_crates.spec(
    package = "prost",
    version = "0.14",
)
sdk_wasm_crates.spec(
    default_features = False,
    package = "prost-types",
    version = "0.14",
)
sdk_wasm_crates.spec(
    package = "extism-pdk",
    version = "1.3.0",
)
sdk_wasm_crates.spec(
    package = "extism-convert",
    version = "1.12.0",
)
sdk_wasm_crates.spec(
    package = "lazy_static",
    version = "1.5.0",
)
sdk_wasm_crates.spec(
    package = "serde",
    version = "1.0.219",
)
sdk_wasm_crates.spec(
    package = "serde_json",
    version = "1.0.145",
)
sdk_wasm_crates.spec(
    default_features = False,
    features = [
        "rt",
        "time",
        "sync",
        "macros",
    ],
    package = "tokio",
    version = "1.48.0",
)
sdk_wasm_crates.spec(
    default_features = False,
    features = ["attributes"],
    package = "tracing",
    version = "0.1.41",
)
sdk_wasm_crates.spec(
    package = "protoc-gen-prost",
    version = "0.3.1",
)
sdk_wasm_crates.annotation(
    crate = "protoc-gen-prost",
    gen_binaries = ["protoc-gen-prost"],
)
sdk_wasm_crates.from_specs(
    name = "sdk_wasm_crates",
    host_tools = "@mooync_edk_host_tools",
    supported_platform_triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "aarch64-apple-darwin",
        "wasm32-wasip1",
    ],
)
use_repo(sdk_wasm_crates, "sdk_wasm_crates")

host_crates = use_extension("@rules_rust//crate_universe:extension.bzl", "crate", isolate = True)
host_crates.spec(
    package = "mdbook-tabs",
    version = "0.1.3",
)
host_crates.annotation(
    crate = "mdbook-tabs",
    gen_binaries = ["mdbook-tabs"],
)
host_crates.from_specs(
    name = "host_crates",
    host_tools = "@mooync_edk_host_tools",
    supported_platform_triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "aarch64-apple-darwin",
    ],
)
use_repo(host_crates, "host_crates")

register_toolchains("//prost_toolchain:prost_toolchain_wasi")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi_moounit",
    python_version = "3.11",
    requirements_lock = "//moounit:requirements_lock.txt",
)
pip.parse(
    hub_name = "pip_deps",
    python_version = "3.11",
    requirements_lock = "//tools:requirements.txt",
)
use_repo(pip, "pypi_moounit", "pip_deps")
