#!/bin/bash
set -o errexit

# --- Arguments ---
SAVED_FILE="$1"
WORKSPACE_ROOT="$2"
OUTPUT_BASE="/tmp/bazel-rust-analyzer"

# --- JSON Wrappers for non-JSON errors ---
MSG_PREFIX='{"reason":"compiler-message","package_id":"","target":{"kind":[""],"crate_types":[""],"name":"","src_path":"","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"'
MSG_SUFFIX='","children":[],"code":null,"level":"error","message":""}}'

# --- 1. Fix Directory & Calculate Paths ---
if [ -n "$WORKSPACE_ROOT" ]; then
    cd "$WORKSPACE_ROOT"
fi
REL_PATH="${SAVED_FILE#$WORKSPACE_ROOT/}"

# Location where rules_rust dumps raw compiler stderr
# Note: "_main" might be different if you are not using bzlmod, but usually correct for Bazel 6+
ACTIONS_DIR="${OUTPUT_BASE}/execroot/_main/bazel-out/_tmp/actions"

run_analyzer() {
  # --- 2. Find Target Package ---
  PACKAGE_PATH=$(bazel query --output=package "$REL_PATH" 2>/dev/null || true)

  if [ -n "$PACKAGE_PATH" ]; then
    BAZEL_TARGET="//${PACKAGE_PATH}:all"
  else
    BAZEL_TARGET="//$(dirname "$REL_PATH"):all"
  fi

  # --- 3. CLEANUP OLD LOGS (Critical!) ---
  # If we don't clear this, you might read errors from 3 builds ago.
  rm -rf "$ACTIONS_DIR"

  set +o errexit
  
  # Build Command
  # We fail silently here because we want to parse the logs ourselves.
  bazel --output_base="${OUTPUT_BASE}" build \
    --@rules_rust//:error_format=json \
    "${BAZEL_TARGET}" >/dev/null 2>&1
  
  RC=$?
  set -o errexit

  # --- 4. Parse The Logs ---
  if [[ "$RC" -ne 0 ]]; then
    # Find all stderr files generated by this build
    if [ -d "$ACTIONS_DIR" ]; then
        find "$ACTIONS_DIR" -name "stderr-*" -type f | while read -r error_file; do
            while read -r line; do
                if [[ "$line" == \{* ]]; then
                    # === JSON LINE ===
                    # Prepend Workspace Root to file paths
                    # This turns "ui/leptos/src/lib.rs" -> "/abs/path/to/repo/ui/leptos/src/lib.rs"
                    FIXED_LINE=$(echo "$line" | sed "s|\"file_name\":\"|\"file_name\":\"$WORKSPACE_ROOT/|g")
                    
                    if [[ "$FIXED_LINE" == *'"reason":"compiler-message"'* ]]; then
                        echo "$FIXED_LINE"
                    else
                        # Wrap raw compiler diagnostics in cargo's compiler-message structure
                        # so that rust-analyzer can parse them.
                        echo '{"reason":"compiler-message","package_id":"","target":{"kind":["lib"],"crate_types":["rlib"],"name":"","src_path":"","edition":"2021","doc":true,"doctest":true,"test":true},"message":'"$FIXED_LINE"'}'
                    fi
                else
                    # === RAW TEXT LINE ===
                    # Wrap generic errors (like linker failures) so the editor shows them
                    ESCAPED_LINE=$(echo "$line" | sed 's/"/\\"/g')
                    echo "${MSG_PREFIX}${ESCAPED_LINE}${MSG_SUFFIX}"
                fi
            done < "$error_file"
        done
    fi
  fi
  
  exit $RC
}

run_analyzer
